{{- if .Values.fibergateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-manager.fullname" . }}-fibergateway
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: gateway
spec:
  replicas: {{ .Values.fibergateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "rancher-manager.selectorLabels" . | nindent 6 }}
      component: gateway
  template:
    metadata:
      labels:
        {{- include "rancher-manager.selectorLabels" . | nindent 8 }}
        component: gateway
    spec:
      containers:
        - name: fibergateway
          image: {{ .Values.fibergateway.image.repository }}:{{ .Values.fibergateway.image.tag }}
          imagePullPolicy: {{ .Values.fibergateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key, $value := .Values.fibergateway.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.fibergateway.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-manager.fullname" . }}-fibergateway
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: gateway
spec:
  type: {{ .Values.fibergateway.service.type }}
  ports:
    - port: {{ .Values.fibergateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rancher-manager.selectorLabels" . | nindent 4 }}
    component: gateway
{{- if .Values.fibergateway.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rancher-manager.fullname" . }}-fibergateway
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: gateway
  {{- with .Values.fibergateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.fibergateway.ingress.className }}
  ingressClassName: {{ .Values.fibergateway.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.fibergateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rancher-manager.fullname" $ }}-fibergateway
                port:
                  number: {{ $.Values.fibergateway.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }} 