{{- if .Values.inventoryservice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-manager.fullname" . }}-inventoryservice
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: microservice
    service: inventoryservice
spec:
  replicas: {{ .Values.inventoryservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "rancher-manager.selectorLabels" . | nindent 6 }}
      component: microservice
      service: inventoryservice
  template:
    metadata:
      labels:
        {{- include "rancher-manager.selectorLabels" . | nindent 8 }}
        component: microservice
        service: inventoryservice
    spec:
      containers:
        - name: inventoryservice
          image: {{ .Values.inventoryservice.image.repository }}:{{ .Values.inventoryservice.image.tag }}
          imagePullPolicy: {{ .Values.inventoryservice.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          env:
            {{- range $key, $value := .Values.inventoryservice.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.inventoryservice.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-manager.fullname" . }}-inventoryservice
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: microservice
    service: inventoryservice
spec:
  type: {{ .Values.inventoryservice.service.type }}
  ports:
    - port: {{ .Values.inventoryservice.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rancher-manager.selectorLabels" . | nindent 4 }}
    component: microservice
    service: inventoryservice
{{- if .Values.inventoryservice.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rancher-manager.fullname" . }}-inventoryservice
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: microservice
    service: inventoryservice
  {{- with .Values.inventoryservice.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.inventoryservice.ingress.className }}
  ingressClassName: {{ .Values.inventoryservice.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.inventoryservice.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rancher-manager.fullname" $ }}-inventoryservice
                port:
                  number: {{ $.Values.inventoryservice.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }} 