{{- if .Values.itemservice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-manager.fullname" . }}-itemservice
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: microservice
    service: itemservice
spec:
  replicas: {{ .Values.itemservice.replicaCount }}
  selector:
    matchLabels:
      {{- include "rancher-manager.selectorLabels" . | nindent 6 }}
      component: microservice
      service: itemservice
  template:
    metadata:
      labels:
        {{- include "rancher-manager.selectorLabels" . | nindent 8 }}
        component: microservice
        service: itemservice
    spec:
      containers:
        - name: itemservice
          image: {{ .Values.itemservice.image.repository }}:{{ .Values.itemservice.image.tag }}
          imagePullPolicy: {{ .Values.itemservice.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
            - name: grpc
              containerPort: 50052
              protocol: TCP
          env:
            {{- range $key, $value := .Values.itemservice.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.itemservice.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-manager.fullname" . }}-itemservice
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: microservice
    service: itemservice
spec:
  type: {{ .Values.itemservice.service.type }}
  ports:
    - port: {{ .Values.itemservice.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 50052
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "rancher-manager.selectorLabels" . | nindent 4 }}
    component: microservice
    service: itemservice
{{- if .Values.itemservice.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rancher-manager.fullname" . }}-itemservice
  labels:
    {{- include "rancher-manager.labels" . | nindent 4 }}
    component: microservice
    service: itemservice
  {{- with .Values.itemservice.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.itemservice.ingress.className }}
  ingressClassName: {{ .Values.itemservice.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.itemservice.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "rancher-manager.fullname" $ }}-itemservice
                port:
                  number: {{ $.Values.itemservice.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }} 