apiVersion: v2
name: rancher-manager
description: A Helm chart for Rancher Manager Microservices
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - rancher
  - go
  - fiber
maintainers:
  - name: Rancher Team
    email: team@rancher.com
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: databases.postgresAuth.enabled
    alias: postgres-auth
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: databases.postgresInventory.enabled
    alias: postgres-inventory
  - name: mongodb
    version: 16.5.29
    repository: https://charts.bitnami.com/bitnami
    condition: databases.mongodb.enabled
  - name: redis
    version: 17.10.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 32.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled 